name: Deploy with Custom Domain

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # DNS設定の自動更新（DNSプロバイダーに応じて調整が必要）
    - name: Update DNS Record
      run: |
        # 例：Cloudflare API を使用する場合
        # curl -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
        #   -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        #   -H "Content-Type: application/json" \
        #   --data '{"type":"CNAME","name":"${{ secrets.SUBDOMAIN }}","content":"masuo444.github.io"}'
        echo "DNS setup would go here based on your DNS provider"
    
    # GitHub Pagesの設定
    - name: Configure GitHub Pages
      run: |
        # GitHub API を使用してカスタムドメインを設定
        curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pages \
          -d '{"source":{"branch":"main","path":"/"},"cname":"${{ secrets.SUBDOMAIN }}.${{ secrets.DOMAIN_NAME }}"}'
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: ${{ secrets.SUBDOMAIN }}.${{ secrets.DOMAIN_NAME }}